export declare type Color = string;
export declare type HexEditorTheme = {
    asciiPaddingX: string | number;
    bytePaddingX: string | number;
    rowPaddingY: string | number;
    scrollWidth: string | number;
    cursorBlinkSpeed: string;
    colorBackground: Color;
    colorBackgroundColumnEven: Color;
    colorBackgroundColumnOdd: Color;
    colorBackgroundCursor: Color;
    colorBackgroundCursorHighlight: Color;
    colorBackgroundEven: Color;
    colorBackgroundInactiveCursor: Color;
    colorBackgroundInactiveCursorHighlight: Color;
    colorBackgroundInactiveSelection: Color;
    colorBackgroundInactiveSelectionCursor: Color;
    colorBackgroundLabel: Color;
    colorBackgroundLabelCurrent: Color;
    colorBackgroundOdd: Color;
    colorBackgroundRowEven: Color;
    colorBackgroundRowOdd: Color;
    colorBackgroundSelection: Color;
    colorBackgroundSelectionCursor: Color;
    colorScrollbackTrack: Color;
    colorScrollbackThumb: Color;
    colorScrollbackThumbHover: Color;
    colorText: Color;
    colorTextColumnEven: Color;
    colorTextColumnOdd: Color;
    colorTextCursor: Color;
    colorTextCursorHighlight: Color;
    colorTextEven: Color;
    colorTextInactiveCursor: Color;
    colorTextInactiveCursorHighlight: Color;
    colorTextInactiveSelection: Color;
    colorTextInactiveSelectionCursor: Color;
    colorTextLabel: Color;
    colorTextLabelCurrent: Color;
    colorTextOdd: Color;
    colorTextRowEven: Color;
    colorTextRowOdd: Color;
    colorTextSelection: Color;
    colorTextSelectionCursor: Color;
    fontFamily: string;
    fontSize: string | number;
    gutterWidth: string | number;
    labelPaddingX: string | number;
    textTransform: string;
};
declare const hexEditorTheme: HexEditorTheme;
export default hexEditorTheme;
